### PR TITLE
get inactivity attribute from session creation response

### LINKED ISSUE #216: Get inactivity attribute from Session Creation Response
I want to get the inactivity attribute from the [session creation response](https://xmpp.org/extensions/xep-0124.html#session-response) (bosh). I would add a property to the BOSH prototype (similar as ``wait``) and set it in [bosh.js#L392](https://github.com/strophe/strophejs/blob/master/src/bosh.js#L392). Any thoughts? Interested in a pr?

### PR DESCRIPTION
**Pull request by sualko**
fix #216

Currently this is untested, I will do it tomorrow.

### CODE REVIEW

**Comment by sualko** [comment]
I fixed a c+p error and now it is working.

**Comment by jcbrand** [comment]
Please also update the changelog.

**Comment by sualko** [comment]
Should I squash?

**Comment by jcbrand** [comment]
Thanks, I squashed from Github.

**Pull request merged**
