### PR TITLE
updated documentation based on jsdoc

### PR DESCRIPTION
**Pull request by Reflex-Gravity**
Enables modern code editors to display proper function document.

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks but this change can't be merged until the tooling has been updated to use JSDoc instead of [naturaldocs](https://www.naturaldocs.org/) which is currently being used.

Can you make that change as well?

**Comment by Reflex-Gravity** [comment]
I haven't tried this before. Let me check. If it's possible.

**Comment by jcbrand** [comment]
FWIW, I still think it's worthwhile to move to JSDoc. Will see if I can move this forward sometime.

**Comment by jcbrand** [comment]
Closing in favour of #361

**Pull request closed without merging**
