### PR TITLE
escapeNode & unescapeNode null tolerance

### PR DESCRIPTION
**Pull request by Sudrien**
Working on candy-chat, got some null errors. I'll try and fix those calls, but figure some graceful null handling on this end is good too.

### CODE REVIEW

**Comment by jcbrand** [comment]
I think a better check would be `if (typeof node !== "string")`

**Comment by Sudrien** [comment]
Looking at xep-0029, it would be possible for a valid node value to be interpreted as an integer. So maybe
<pre>if ((typeof node === "string" || typeof node === "number") && node != '' ) { node = String(node); }
else { return null; }</pre>

That might be getting too much into validation that happens in other places, though.

**Comment by jcbrand** [comment]
This should do it:

```
    if (typeof node !== string) { return node; }
```

**Comment by Sudrien** [comment]
Done.

**Comment by jcbrand** [comment]
Thanks!

**Pull request merged**
