### PR TITLE
Permit connecting with an alternative authcid

### PR DESCRIPTION
**Pull request by benlangfeld**
This permits imitation of other users (for example, if usera@example.com is allowed to create a session as userb@example.com, he will provide the JID userb@example.com in <stream:stream to="..." and <bind/>, but use his own credentials in the the <auth/> packet per SASL's separation of authzid and authcid.

### CODE REVIEW

**Comment by benlangfeld** [comment]
This appears to work well for me on [ejabberd](https://github.com/processone/ejabberd/pull/525). Any chance it could be merged?

**Comment by jcbrand** [comment]
Hi @benlangfeld, I'm curious, what's the usecase for this? Is it for users who have multiple XMPP accounts?

**Comment by benlangfeld** [comment]
Either for proxy authentication in general (maybe a set of credentials give access to multiple accounts, maybe certain users can masquerade as other users for testing purposes) or, in my case, to support [MojoAuth](http://mojoauth.mojolingo.com/).

**Comment by benlangfeld** [comment]
Is there a particular schedule for a 1.2.3 release, @jcbrand, or would it be appropriate to request that here?

**Comment by jcbrand** [comment]
So far there aren't many new changes since the last release (1.2.1).

I'm however happy to make a new release for you if you need it.

**Comment by benlangfeld** [comment]
Only so that Candy can depend on a final release. No big deal :)

**Comment by benlangfeld** [comment]
Put a freeze on that request, @jcbrand. I'm [having trouble](https://github.com/candy-chat/candy/pull/385) updating Candy to 1.2.1 anyway.

**Pull request merged**
