### PR TITLE
Move stanza ids from counter based ID to UUID

### PR DESCRIPTION
**Pull request by hobblegobber**
Hello,

I recently came across a bug in conversejs which uses Strophe as it's underlying library. The issue is explained here - https://github.com/jcbrand/converse.js/issues/456

The author recommended that I give a pull request here for the same. I have made a fix to generate UUID instead of counter based ID and there are no failing tests. The practice is also recommended by the XMPP RFC - http://xmpp.org/rfcs/rfc6120.html#streams-attr-id

PS:  I have not edited the documentation/comments above the function. Let me know if they have to be changed too.

### CODE REVIEW

**Comment by Gordin** [comment]
Hi, please make ALL of your changes in the src folder and then generate strophe.js and strophe.min.js from your changes. strophe.js should never be edited directly.

Also, the uuid generation should be refactored so the algorithm appears only once. The code seems fine otherwise I think.

**Comment by hobblegobber** [comment]
Hello, I made the changes in core/src.js and ran make to generate the strophe.js & strophe.min.js files. The strophe files appear to be edited directly because it's in a separate commit(I forgot to run make the first time.)

I will be refactoring the code.

**Comment by hobblegobber** [comment]
Have pushed the changes. Let me know if this is fine.

**Comment by jcbrand** [comment]
I'll merge this later, but I'm going to rewrite the history to remove the changes to strophe.js and strophe.min.js. 

We only want to generate those two files when we make new releases of Strophe.js, not for each pull request, otherwise we bloat the repo with large diffs.

**Comment by hobblegobber** [comment]
Alright, Thanks.

**Comment by jcbrand** [comment]
@hobblegobber You forgot to return the uuids, so `getUniqueId` was always returning `undefined`.

In any case, fixed now and I also made a new release of strophe.js: 1.2.3.

**Comment by hobblegobber** [comment]
Hello, That's my bad. Thanks for the quick fix thought. Cheers.

**Pull request closed without merging**
