### PR TITLE
Support for chinese usernames

### PR DESCRIPTION
**Pull request by jimieweile**
support chinese username

### CODE REVIEW

**Comment by jcbrand** [comment]
@jimieweile This fix is in the wrong place. You placed it in the compiled strophe.js file. That file gets compiled from the individual files in the `./src` directory.

So the right place looks to be `./src/base64.js`.

However, when I added the code there, one of the strophe.js tests fail. Can you please explain what exactly this change does and why it is necessary?

**Comment by mathiasfriman** [comment]
"Can you please explain what exactly this change does and why it is necessary?"

I will give it a shot. JavaScript default to UTF16 character encoding, and the rest of the IT world uses UTF8. This patch converts non-ASCII characters from utf16 to utf8 in order to be able to use them in usernames and passwords. In sweden we have åäöÅÄÖ as "non-standard" letters in our alphabet, and when having them in a password or username, we cannot login using strophe.js. This affects Jitsi-Meet and all other software that rely on strophe.

When the patch is applied, the conversion works and I'm able to login with a password like "FörlåtRäksmörgås8912". Without it, I get a SASL error.

I can confirm that the patch works as intended, however, I have no knowledge on how to make the tests not fail.

**Comment by jcbrand** [comment]
Thanks @mathiasfriman, maybe the failing test is a red herring and it's just the test itself that needs to be updated. I'll take a close look once I have time again.

**Comment by jcbrand** [comment]
I tried this patch again. With it applied, I cannot log in or register new accounts through Strophe.

@mathiasfriman  Which of the authentication mechanisms are you using?

The test that fails tests SCRAM SHA1 authentication. So it definitely shouldn't fail. That's also the scheme I was using to try and log in.

**Comment by jcbrand** [comment]
@mathiasfriman I'm pretty sure the above patch was only ever tested with SASL PLAIN auth, because that appears to be the only mechanism for which it worked.

I made a few commits and this problem should now be fixed for PLAIN, MD5 and SHA1. I'd appreciate it if you could give the master branch a test to confirm that it also works for you.

**Pull request merged**
