### PR TITLE
Add support for the Asynchronous Module Definition (AMD) and require.js

### PR DESCRIPTION
**Pull request by jcbrand**
This pull request adds support for AMD which allows better integration with projects that use require.js for module and loading and dependency management.

The strophe.js file as well as the files under ./src/ should all still work in the traditional non-AMD usecases.

All tests pass and I also tested both the AMD and non-AMD usecases with converse.js

See #29

### CODE REVIEW

**Comment by benlangfeld** [comment]
Use in a non-AMD case appears broken. The callback in the wrapper which sets `window.Strophe` does not have `Strophe` defined. If I manually edit to look like this, I get further:

```javascript
    _sendRestart: function ()
    {
        clearTimeout(this._conn._idleTimeout);
        this._conn._onIdle.bind(this._conn)();
    }
};

/* jshint ignore:start */
if (callback) {
    return callback(Strophe, $build, $msg, $iq, $pres);
}
return Strophe;
}));


})(function (Strophe, build, msg, iq, pres) {
    window.Strophe = Strophe;
    window.$build = build;
    window.$msg = msg;
    window.$iq = iq;
    window.$pres = pres;
});
/* jshint ignore:end */
```

Unfortunately, not much further. strophejs-plugins assumes that `window.Strophe` is defined before it loads, and of course it is not.

**Comment by jcbrand** [comment]
The non-AMD case worked fine for me when I tested it with converse.js's ``non_amd.html``.

It's not clear from the code snippet above what you've actually changed.

**Comment by benlangfeld** [comment]
I couldn't figure out the structure in the source files, but edited the concatenated source as so:

```diff
diff --git a/strophe.js b/strophe.js
index 9f13757..e76e5fe 100644
--- a/strophe.js
+++ b/strophe.js
@@ -5305,12 +5305,12 @@ Strophe.Websocket.prototype = {
     }
 };
 return Strophe;
-}));

 /* jshint ignore:start */
 if (callback) {
     return callback(Strophe, $build, $msg, $iq, $pres);
 }
+}));


 })(function (Strophe, build, msg, iq, pres) {
```

**Comment by benlangfeld** [comment]
If you want to see how this breaks a non-AMD consumer of Strophe, check out https://github.com/candy-chat/candy/pull/385.

**Comment by benlangfeld** [comment]
Do you have any idea what might be wrong here or how I might hope to resolve this, @jcbrand?

**Comment by jcbrand** [comment]
@benlangfeld You say in that ticket that the app works and just the tests fail.

Perhaps the tests need to be changed? I don't know anything about the Candy tests or what assumptions they make.

Here's the non AMD version of converse.js, you can try it out for yourself to see that it works: https://conversejs.org/non_amd.html

In the developer console you'll see that Strophe is defined.

**Pull request merged**
