### PR TITLE
remove duplicate of kill websocket

### PR DESCRIPTION
**Pull request by awMinor**

### CODE REVIEW

**Comment by jcbrand** [comment]
Please explain why you think that line should be removed. Also, if it's not needed, why do you comment it out instead of just removing it?

**Comment by awMinor** [comment]
because when I use disconnect with this row I have message that websocket already closed and in this method I try to send data through it.

**Comment by jcbrand** [comment]
Strophe.js is not the right place to make this change, that file is built from the files in `./src/`.
If it's websocket related, then the relevant line is most likely in `./src/websocket.js`

However, that said, it's not clear to me that this is the right fix for your problem. The `_disconnect` method actually checks `this.socket.readyState !== WebSocket.CLOSED` and it's not clear to me when and where the websocket connection would already have been closed.

@Gordin Any ideas on this?

**Comment by awMinor** [comment]
http://i.imgur.com/uDLIHMa.png

Here is screenshot of error with this row

**Comment by sonnyp** [comment]
related https://github.com/strophe/strophejs/pull/145

@awMinor I think you're running an outdated version of Strophe

**Pull request closed without merging**
