### PR TITLE
Add minified strophe to npm module

### PR DESCRIPTION
**Pull request by dwilson6**

### CODE REVIEW

**Comment by jcbrand** [comment]
Actually, over time I've come to the conclusion that minified files shouldn't be included in version control. They bloat the repository because the diff between versions is so large.

Why is it important for you to have a minified file via npm? Generally multiple files get bundled and minified for a project, so individual minified files are not really necessary.

**Comment by dwilson6** [comment]
Yeah, I was going back and forth on this.  I was trying to use it in a project (jitsi/jitsi-meet) which has the minified js checked into its repo.  I was debating adding it to the bundle instead of copying the file into libs but was trying to not add bower deps to the repo.  I will probably just end up bundling it in so I'll just close this.  The other issue I'm running into is that strophe-plugins npm module is really old.

**Comment by jcbrand** [comment]
I made a new npm release for you: https://www.npmjs.com/package/strophejs-plugins

**Comment by dwilson6** [comment]
Thanks for the quick response, it looks like the files section in package.json doesn't have any of the plugin files: https://github.com/strophe/strophejs-plugins/blob/master/package.json

**Comment by jcbrand** [comment]
@dwilson6 Can you please make a pull request for that?

**Comment by dwilson6** [comment]
Done https://github.com/strophe/strophejs-plugins/pull/75

**Pull request closed without merging**
