### PR TITLE
Adding SASL OAuth Bearer authentication

### PR DESCRIPTION
**Pull request by guusdk**
Introduces basic support for the OAUTHBEARER SASL mechanism as specified in
https://tools.ietf.org/html/rfc7628

### CODE REVIEW

**Comment by jcbrand** [comment]
Hi @guusdk Thanks for the pull request. 

I'm curious, are you using this with an XMPP server acting as authorization server as well, or only as a resource server?

If you're using it only as a resource server, then it would still need to validate the token with the auth server, correct?

**Comment by guusdk** [comment]
I'm still in prototyping stage, but there's a lot of chicken/egg going on, when you want to add support to a server but you don't have a client to test things with. I'm not sure, but your client might be the first with OAuth Bearer support :) I'm desperately looking for feedback though, as I hate being the implementation party of both ends of the equation.

If the XMPP server were to act as an authorization server, I'd have to find a way for clients to retrieve an access token via XMPP. Not sure how to do that (RFC7628 does not account for that).

For now, I'm currently working with an external authorization server, where clients need to obtain a access token from 'out of band'. Using that token, they log into the XMPP server (using the code from this PR, which utilizes the SASL mechanism ). Under the hood, the XMPP server verifies the code with authorization server.

**Comment by jcbrand** [comment]
@guusdk I've been thinking of doing pretty much the same thing, so I'm glad you added this. Although, I assumed one could get away with just using one of the existing SASL mechanisms. I wasn't even aware that RFC7628 existed.

I guess one reason for implementing this would be so that the server can advertise various SASL mechanisms it supports and that OAuth is then just one of multiple that the client can choose from. Am I right, or is there more to it then that?

Is the server-side stuff you're doing open source?

**Comment by guusdk** [comment]
You're right. The XMPP server broadcasts support for the OAUTHBEARER SASL mechanism, amongst others. Depending on client preference (in Strophe's case, the numeric priority), the supplied credentials are interpreted as digests, tokens, or whatever is applicable to the SASL mechanism in use.

I'm not sure yet if my client will let me open-source the solution. I'd have to check. Another challenge would be the tight integration with a very specific authorization server implementation. That's not ideal either.

**Comment by guusdk** [comment]
@jcbrand I now noticed that I didn't update the pre-built artifacts that are in git (I was thoroughly confused when my stuff didn't work any longer - turns out I used a fresh git clone. Could you / would you?

**Comment by jcbrand** [comment]
I'm not sure what you mean with "pre-built artiffacts", do you mean the `strophe.js` and `strophe.min.js` bundles?

**Comment by guusdk** [comment]
Yes.

**Comment by jcbrand** [comment]
Sure, I'll generate those again just before the next release. If you need them in the meantime, you can run `make strophe.js` or `make strophe.min.js`.

**Comment by guusdk** [comment]
Yeah, I did that by now (but hadn't set up an environment with node / npm
at the time I was asking). Thanks though!

**Comment by Zash** [comment]
If you're still looking for something to test against, Prosody 13.0.0 supports OAUTHBEARER and can operate either as both [resource and authorization server](https://modules.prosody.im/mod_http_oauth2.html) or as a [resource server](https://modules.prosody.im/mod_auth_oauth_external.html) pointed at another authorization server.

**Pull request merged**
