### PR TITLE
Fix for React-Native: parse responseText if responseXML is missing

### PR DESCRIPTION
**Pull request by joeytwiddle**
We are using create-react-native-app and Expo.

Responses which worked fine in the browser did not work in the iOS Simulator, running Expo, because `responseXML` was undefined.

Our solution was to simple parse `responseText` ourselves.

### CODE REVIEW

**Comment by joeytwiddle** [comment]
Sorry that the build is failing. I don't know why. It might be because this is forked from `v1.2.14` not from the latest commit.

**Comment by joeytwiddle** [comment]
OK the failed test was relevant! During that test, the parser was returning a `null` documentElement, without any error.

I am turning that into an error, so the test passes again.

**Comment by joeytwiddle** [comment]
This PR only includes the change to the source code. Should I also commit the change it makes to `strophe.js` and `strophe.min.js` after `make dist`?

**Comment by jcbrand** [comment]
Looking good, thanks!

**Pull request merged**
