### PR TITLE
move phantomjs dependencies to devDependencies

### PR DESCRIPTION
**Pull request by akatov**
otherwise projects depending on strophe will have to install a specific phantomjs version also...

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks!

**Comment by juliendangers** [comment]
:heart: could you release a new version on npm please ?

**Comment by jcbrand** [comment]
I recently made a new release, do you need a version with just this change?

**Comment by juliendangers** [comment]
It would be great. `npm install --production` will be faster with that change

**Comment by juliendangers** [comment]
any news on a new release ?

**Comment by jcbrand** [comment]
I don't really see the point in doing it, especially since my time is quite limited currently. How often do you run `npm install --production` that it's actually an issue for you if it takes a little longer?

**Comment by juliendangers** [comment]
every time we have a deploy (around 10 times a day in production, and 150 times a day for developers team). The main issue is that phantomjs needs a native build, so even if we're using a distant cache, `node rebuild` is triggered :/

**Comment by jcbrand** [comment]
OK, done. https://www.npmjs.com/package/strophe.js

**Comment by juliendangers** [comment]
:heart: thanks a lot !

**Pull request merged**
