### PR TITLE
allow empty expectedFrom according to W3C DOM 3 Specification (so it …

### PR DESCRIPTION
**Pull request by aksonov**
I've replaced expectedFrom === null to !expectedFrom for compatibility with both DOM 3 and DOM 4 standards. Then i did make to generate bundles, however more code is changed there?

### CODE REVIEW

**Comment by jcbrand** [comment]
Thanks @aksonov, it just means that the strophe.js file hasn't been generated for a while. I usually only generate it before I make a new release.

**Comment by aksonov** [comment]
Thanks, but looks like latest generated strophe.js version (1.2.3) brakes compatibility within nodejs environment. 1.2.2 worked fine from npm (without introducing 'utils' var)

TypeError: Cannot read property 'utf16to8' of undefined
    at Object.Strophe.SASLSHA1.onChallenge (/Users/aksonov/Documents/rn-chat/node_modules/strophe.js/strophe.js:3862:30)
    at Object.Strophe.Connection.authenticate (/Users/aksonov/Documents/rn-chat/node_modules/strophe.js/strophe.js:3225:47)
    at Object.Strophe.Connection._connect_cb (/Users/aksonov/Documents/rn-chat/node_modules/strophe.js/strophe.js:3170:18)
    at Object.Strophe.Websocket._connect_cb_wrapper (/Users/aksonov/Documents/rn-chat/node_modules/strophe.js/strophe.js:5242:24)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/aksonov/Documents/rn-chat/node_modules/yaeti/lib/EventTarget.js:117:12)
    at W3CWebSocket.onMessage (/Users/aksonov/Documents/rn-chat/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/aksonov/Documents/rn-chat/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:77:13)
    at WebSocketConnection.emit (events.js:169:7)
    at WebSocketConnection.processFrame (/Users/aksonov/Documents/rn-chat/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/aksonov/Documents/rn-chat/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

**Comment by jcbrand** [comment]
Oh, it's probably because utils.js (which is new) isn't included in the built file.

**Comment by aksonov** [comment]
Strange, why all tests passed then? Or they don't use generated strophe.js?

**Comment by jcbrand** [comment]
yes, the don't.

**Comment by aksonov** [comment]
Will you fix it?

Pavel.

**Comment by jcbrand** [comment]
Yes, eventually if no-one else does. I can't get to it today though.

**Comment by aksonov** [comment]
No problem here, submitted https://github.com/strophe/strophejs/pull/163

**Pull request merged**
